// Code generated by MockGen. DO NOT EDIT.
// Source: transport.go
//
// Generated by this command:
//
//	mockgen -source=transport.go -destination=mocks/transport.mock.go Transport
//

// Package mock_transport is a generated GoMock package.
package mock_transport

import (
	context "context"
	structs "github.com/kestfor/in-memorydb/pkg/structs"
	types "github.com/kestfor/in-memorydb/pkg/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// GetVersion mocks base method.
func (m *MockTransport) GetVersion(ctx context.Context, addr string) (types.VectorClock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, addr)
	ret0, _ := ret[0].(types.VectorClock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockTransportMockRecorder) GetVersion(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockTransport)(nil).GetVersion), ctx, addr)
}

// GetKeyDigests mocks base method.
func (m *MockTransport) GetKeyDigests(ctx context.Context, addr string, bucket uint32) (map[string]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyDigests", ctx, addr, bucket)
	ret0, _ := ret[0].(map[string]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyDigests indicates an expected call of GetKeyDigests.
func (mr *MockTransportMockRecorder) GetKeyDigests(ctx, addr, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyDigests", reflect.TypeOf((*MockTransport)(nil).GetKeyDigests), ctx, addr, bucket)
}

// PullKeyStates mocks base method.
func (m *MockTransport) PullKeyStates(ctx context.Context, addr string, keys []string) ([]*types.KeyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullKeyStates", ctx, addr, keys)
	ret0, _ := ret[0].([]*types.KeyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullKeyStates indicates an expected call of PullKeyStates.
func (mr *MockTransportMockRecorder) PullKeyStates(ctx, addr, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullKeyStates", reflect.TypeOf((*MockTransport)(nil).PullKeyStates), ctx, addr, keys)
}

// Pull mocks base method.
func (m *MockTransport) Pull(ctx context.Context, addr string, versions map[string][]structs.Range) ([]*types.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, addr, versions)
	ret0, _ := ret[0].([]*types.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockTransportMockRecorder) Pull(ctx, addr, versions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockTransport)(nil).Pull), ctx, addr, versions)
}

// Send mocks base method.
func (m *MockTransport) Send(ctx context.Context, addr string, data []*types.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, addr, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTransportMockRecorder) Send(ctx, addr, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTransport)(nil).Send), ctx, addr, data)
}
