// Code generated by MockGen. DO NOT EDIT.
// Source: gossip.go
//
// Generated by this command:
//
//	mockgen -source=gossip.go -destination=mocks/gossip.mock.go Gossip
//

// Package mock_gossip is a generated GoMock package.
package mock_gossip

import (
	context "context"
	storage "in-memorydb/pkg/storage"
	gossip "in-memorydb/pkg/storage/gossip"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGossip is a mock of Gossip interface.
type MockGossip struct {
	ctrl     *gomock.Controller
	recorder *MockGossipMockRecorder
	isgomock struct{}
}

// MockGossipMockRecorder is the mock recorder for MockGossip.
type MockGossipMockRecorder struct {
	mock *MockGossip
}

// NewMockGossip creates a new mock instance.
func NewMockGossip(ctrl *gomock.Controller) *MockGossip {
	mock := &MockGossip{ctrl: ctrl}
	mock.recorder = &MockGossipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGossip) EXPECT() *MockGossipMockRecorder {
	return m.recorder
}

// AsyncSend mocks base method.
func (m *MockGossip) AsyncSend(ctx context.Context, data []*storage.Update) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncSend", ctx, data)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// AsyncSend indicates an expected call of AsyncSend.
func (mr *MockGossipMockRecorder) AsyncSend(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncSend", reflect.TypeOf((*MockGossip)(nil).AsyncSend), ctx, data)
}

// GetVersionVector mocks base method.
func (m *MockGossip) GetVersionVector(ctx context.Context) (gossip.VersionVectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionVector", ctx)
	ret0, _ := ret[0].(gossip.VersionVectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionVector indicates an expected call of GetVersionVector.
func (mr *MockGossipMockRecorder) GetVersionVector(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionVector", reflect.TypeOf((*MockGossip)(nil).GetVersionVector), ctx)
}

// Pull mocks base method.
func (m *MockGossip) Pull(ctx context.Context, versions storage.Version) ([]*storage.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, versions)
	ret0, _ := ret[0].([]*storage.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockGossipMockRecorder) Pull(ctx, versions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockGossip)(nil).Pull), ctx, versions)
}

// Send mocks base method.
func (m *MockGossip) Send(ctx context.Context, data []*storage.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockGossipMockRecorder) Send(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockGossip)(nil).Send), ctx, data)
}
