// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/storage/transport/grpc/api.proto

package transportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED UpdateType = 0
	UpdateType_UPDATE_TYPE_SET         UpdateType = 1
	UpdateType_UPDATE_TYPE_DELETE      UpdateType = 2
	UpdateType_UPDATE_TYPE_DELTA       UpdateType = 3
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "UPDATE_TYPE_SET",
		2: "UPDATE_TYPE_DELETE",
		3: "UPDATE_TYPE_DELTA",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED": 0,
		"UPDATE_TYPE_SET":         1,
		"UPDATE_TYPE_DELETE":      2,
		"UPDATE_TYPE_DELTA":       3,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_storage_transport_grpc_api_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_pkg_storage_transport_grpc_api_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{0}
}

type TimeStamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      uint64                 `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Lamport       uint64                 `protobuf:"varint,2,opt,name=lamport,proto3" json:"lamport,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeStamp) Reset() {
	*x = TimeStamp{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStamp) ProtoMessage() {}

func (x *TimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStamp.ProtoReflect.Descriptor instead.
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{0}
}

func (x *TimeStamp) GetWallTime() uint64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *TimeStamp) GetLamport() uint64 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

func (x *TimeStamp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{1}
}

func (x *Range) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Type          UpdateType             `protobuf:"varint,2,opt,name=type,proto3,enum=transport.UpdateType" json:"type,omitempty"`
	Ts            *TimeStamp             `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Range         *Range                 `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	CrdtType      string                 `protobuf:"bytes,7,opt,name=crdt_type,json=crdtType,proto3" json:"crdt_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{2}
}

func (x *Update) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Update) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *Update) GetTs() *TimeStamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Update) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Update) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Update) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Update) GetCrdtType() string {
	if x != nil {
		return x.CrdtType
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       map[string]*Range      `protobuf:"bytes,1,rep,name=version,proto3" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetVersion() map[string]*Range {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*Update              `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetUpdates() []*Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*Update              `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{5}
}

func (x *PublishRequest) GetUpdates() []*Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetVersionVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       map[string]*Range      `protobuf:"bytes,1,rep,name=version,proto3" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionVectorResponse) Reset() {
	*x = GetVersionVectorResponse{}
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionVectorResponse) ProtoMessage() {}

func (x *GetVersionVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_transport_grpc_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionVectorResponse.ProtoReflect.Descriptor instead.
func (*GetVersionVectorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_storage_transport_grpc_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetVersionVectorResponse) GetVersion() map[string]*Range {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_pkg_storage_transport_grpc_api_proto protoreflect.FileDescriptor

const file_pkg_storage_transport_grpc_api_proto_rawDesc = "" +
	"\n" +
	"$pkg/storage/transport/grpc/api.proto\x12\ttransport\x1a\x1bgoogle/protobuf/empty.proto\"R\n" +
	"\tTimeStamp\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x04R\bwallTime\x12\x18\n" +
	"\alamport\x18\x02 \x01(\x04R\alamport\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\xe3\x01\n" +
	"\x06Update\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.transport.UpdateTypeR\x04type\x12$\n" +
	"\x02ts\x18\x03 \x01(\v2\x14.transport.TimeStampR\x02ts\x12&\n" +
	"\x05range\x18\x04 \x01(\v2\x10.transport.RangeR\x05range\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1b\n" +
	"\tcrdt_type\x18\a \x01(\tR\bcrdtType\"\x98\x01\n" +
	"\n" +
	"GetRequest\x12<\n" +
	"\aversion\x18\x01 \x03(\v2\".transport.GetRequest.VersionEntryR\aversion\x1aL\n" +
	"\fVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.transport.RangeR\x05value:\x028\x01\":\n" +
	"\vGetResponse\x12+\n" +
	"\aupdates\x18\x01 \x03(\v2\x11.transport.UpdateR\aupdates\"=\n" +
	"\x0ePublishRequest\x12+\n" +
	"\aupdates\x18\x01 \x03(\v2\x11.transport.UpdateR\aupdates\"\xb4\x01\n" +
	"\x18GetVersionVectorResponse\x12J\n" +
	"\aversion\x18\x01 \x03(\v20.transport.GetVersionVectorResponse.VersionEntryR\aversion\x1aL\n" +
	"\fVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.transport.RangeR\x05value:\x028\x01*m\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUPDATE_TYPE_SET\x10\x01\x12\x16\n" +
	"\x12UPDATE_TYPE_DELETE\x10\x02\x12\x15\n" +
	"\x11UPDATE_TYPE_DELTA\x10\x032\xce\x01\n" +
	"\aUpdates\x12<\n" +
	"\aPublish\x12\x19.transport.PublishRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x03Get\x12\x15.transport.GetRequest\x1a\x16.transport.GetResponse\x12O\n" +
	"\x10GetVersionVector\x12\x16.google.protobuf.Empty\x1a#.transport.GetVersionVectorResponseB(Z&pkg/storage/transport/grpc/transportpbb\x06proto3"

var (
	file_pkg_storage_transport_grpc_api_proto_rawDescOnce sync.Once
	file_pkg_storage_transport_grpc_api_proto_rawDescData []byte
)

func file_pkg_storage_transport_grpc_api_proto_rawDescGZIP() []byte {
	file_pkg_storage_transport_grpc_api_proto_rawDescOnce.Do(func() {
		file_pkg_storage_transport_grpc_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_storage_transport_grpc_api_proto_rawDesc), len(file_pkg_storage_transport_grpc_api_proto_rawDesc)))
	})
	return file_pkg_storage_transport_grpc_api_proto_rawDescData
}

var file_pkg_storage_transport_grpc_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_storage_transport_grpc_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_storage_transport_grpc_api_proto_goTypes = []any{
	(UpdateType)(0),                  // 0: transport.UpdateType
	(*TimeStamp)(nil),                // 1: transport.TimeStamp
	(*Range)(nil),                    // 2: transport.Range
	(*Update)(nil),                   // 3: transport.Update
	(*GetRequest)(nil),               // 4: transport.GetRequest
	(*GetResponse)(nil),              // 5: transport.GetResponse
	(*PublishRequest)(nil),           // 6: transport.PublishRequest
	(*GetVersionVectorResponse)(nil), // 7: transport.GetVersionVectorResponse
	nil,                              // 8: transport.GetRequest.VersionEntry
	nil,                              // 9: transport.GetVersionVectorResponse.VersionEntry
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_pkg_storage_transport_grpc_api_proto_depIdxs = []int32{
	0,  // 0: transport.Update.type:type_name -> transport.UpdateType
	1,  // 1: transport.Update.ts:type_name -> transport.TimeStamp
	2,  // 2: transport.Update.range:type_name -> transport.Range
	8,  // 3: transport.GetRequest.version:type_name -> transport.GetRequest.VersionEntry
	3,  // 4: transport.GetResponse.updates:type_name -> transport.Update
	3,  // 5: transport.PublishRequest.updates:type_name -> transport.Update
	9,  // 6: transport.GetVersionVectorResponse.version:type_name -> transport.GetVersionVectorResponse.VersionEntry
	2,  // 7: transport.GetRequest.VersionEntry.value:type_name -> transport.Range
	2,  // 8: transport.GetVersionVectorResponse.VersionEntry.value:type_name -> transport.Range
	6,  // 9: transport.Updates.Publish:input_type -> transport.PublishRequest
	4,  // 10: transport.Updates.Get:input_type -> transport.GetRequest
	10, // 11: transport.Updates.GetVersionVector:input_type -> google.protobuf.Empty
	10, // 12: transport.Updates.Publish:output_type -> google.protobuf.Empty
	5,  // 13: transport.Updates.Get:output_type -> transport.GetResponse
	7,  // 14: transport.Updates.GetVersionVector:output_type -> transport.GetVersionVectorResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_storage_transport_grpc_api_proto_init() }
func file_pkg_storage_transport_grpc_api_proto_init() {
	if File_pkg_storage_transport_grpc_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_storage_transport_grpc_api_proto_rawDesc), len(file_pkg_storage_transport_grpc_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_storage_transport_grpc_api_proto_goTypes,
		DependencyIndexes: file_pkg_storage_transport_grpc_api_proto_depIdxs,
		EnumInfos:         file_pkg_storage_transport_grpc_api_proto_enumTypes,
		MessageInfos:      file_pkg_storage_transport_grpc_api_proto_msgTypes,
	}.Build()
	File_pkg_storage_transport_grpc_api_proto = out.File
	file_pkg_storage_transport_grpc_api_proto_goTypes = nil
	file_pkg_storage_transport_grpc_api_proto_depIdxs = nil
}
