# этот конфиг можно использовать к примеру как шаблон для докер сервисов, добавляя уникальные для ноды данные через ENV

node:
  bind_address: "0.0.0.0"
  port: 8080
gossip:
  bind_address: "0.0.0.0"
  port: 8081
  fanout: 3
  interval: 10s
  retries: 2
membership:
  port: 8082
engine:
  shards_num: 256
persistence:
  enabled: false
  wal:
    path: ./wal_data_1
    flush_interval: 1s
    batch_size: 5000
    segment_threshold: 10000

security:
  mode: disabled

trace:
  enabled: false
  endpoint: 192.168.0.14:4318
