node:
  id: "node7"
  bind_address: "0.0.0.0"
  port: 50051
seeds:
  - "node-2"
  - "node-3"
gossip:
  bind_address: "0.0.0.0"
  port: 50052
  fanout: 3
  interval: 30000
  retries: 2
membership:
  port: 50053
persistence:
  wal:
    path: ./wal_data
    segment_threshold: 1000
trace:
#endpoint: 192.168.56.1:4318
#enable: true
