// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/transport/grpc/transportpb/api.proto

package transportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{0}
}

func (x *Range) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type RangeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranges        []*Range               `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeList) Reset() {
	*x = RangeList{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeList) ProtoMessage() {}

func (x *RangeList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeList.ProtoReflect.Descriptor instead.
func (*RangeList) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{1}
}

func (x *RangeList) GetRanges() []*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      map[string]*RangeList  `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetVersions() map[string]*RangeList {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       [][]byte               `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetUpdates() [][]byte {
	if x != nil {
		return x.Updates
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       [][]byte               `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRequest) GetUpdates() [][]byte {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetVersionVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorClock   map[string]uint64      `protobuf:"bytes,1,rep,name=VectorClock,proto3" json:"VectorClock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionVectorResponse) Reset() {
	*x = GetVersionVectorResponse{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionVectorResponse) ProtoMessage() {}

func (x *GetVersionVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionVectorResponse.ProtoReflect.Descriptor instead.
func (*GetVersionVectorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetVersionVectorResponse) GetVectorClock() map[string]uint64 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type RestoreSeqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSeqRequest) Reset() {
	*x = RestoreSeqRequest{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSeqRequest) ProtoMessage() {}

func (x *RestoreSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSeqRequest.ProtoReflect.Descriptor instead.
func (*RestoreSeqRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreSeqRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetKeyDigestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        uint32                 `protobuf:"varint,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyDigestsRequest) Reset() {
	*x = GetKeyDigestsRequest{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyDigestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyDigestsRequest) ProtoMessage() {}

func (x *GetKeyDigestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyDigestsRequest.ProtoReflect.Descriptor instead.
func (*GetKeyDigestsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetKeyDigestsRequest) GetBucket() uint32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

type GetKeyDigestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       map[string]uint64      `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyDigestsResponse) Reset() {
	*x = GetKeyDigestsResponse{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyDigestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyDigestsResponse) ProtoMessage() {}

func (x *GetKeyDigestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyDigestsResponse.ProtoReflect.Descriptor instead.
func (*GetKeyDigestsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetKeyDigestsResponse) GetDigests() map[string]uint64 {
	if x != nil {
		return x.Digests
	}
	return nil
}

type PullKeyStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullKeyStatesRequest) Reset() {
	*x = PullKeyStatesRequest{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullKeyStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullKeyStatesRequest) ProtoMessage() {}

func (x *PullKeyStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullKeyStatesRequest.ProtoReflect.Descriptor instead.
func (*PullKeyStatesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{9}
}

func (x *PullKeyStatesRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyStateProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Key                 string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CrdtType            string                 `protobuf:"bytes,2,opt,name=crdt_type,json=crdtType,proto3" json:"crdt_type,omitempty"`
	State               []byte                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Tombstone           bool                   `protobuf:"varint,4,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	SetTimeStampWall    uint64                 `protobuf:"varint,5,opt,name=set_time_stamp_wall,json=setTimeStampWall,proto3" json:"set_time_stamp_wall,omitempty"`
	SetTimeStampLamport uint64                 `protobuf:"varint,6,opt,name=set_time_stamp_lamport,json=setTimeStampLamport,proto3" json:"set_time_stamp_lamport,omitempty"`
	SetTimeStampId      string                 `protobuf:"bytes,7,opt,name=set_time_stamp_id,json=setTimeStampId,proto3" json:"set_time_stamp_id,omitempty"`
	Vc                  map[string]uint64      `protobuf:"bytes,8,rep,name=vc,proto3" json:"vc,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *KeyStateProto) Reset() {
	*x = KeyStateProto{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyStateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyStateProto) ProtoMessage() {}

func (x *KeyStateProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyStateProto.ProtoReflect.Descriptor instead.
func (*KeyStateProto) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{10}
}

func (x *KeyStateProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyStateProto) GetCrdtType() string {
	if x != nil {
		return x.CrdtType
	}
	return ""
}

func (x *KeyStateProto) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *KeyStateProto) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *KeyStateProto) GetSetTimeStampWall() uint64 {
	if x != nil {
		return x.SetTimeStampWall
	}
	return 0
}

func (x *KeyStateProto) GetSetTimeStampLamport() uint64 {
	if x != nil {
		return x.SetTimeStampLamport
	}
	return 0
}

func (x *KeyStateProto) GetSetTimeStampId() string {
	if x != nil {
		return x.SetTimeStampId
	}
	return ""
}

func (x *KeyStateProto) GetVc() map[string]uint64 {
	if x != nil {
		return x.Vc
	}
	return nil
}

type PullKeyStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyStates     []*KeyStateProto       `protobuf:"bytes,1,rep,name=key_states,json=keyStates,proto3" json:"key_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullKeyStatesResponse) Reset() {
	*x = PullKeyStatesResponse{}
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullKeyStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullKeyStatesResponse) ProtoMessage() {}

func (x *PullKeyStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpc_transportpb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullKeyStatesResponse.ProtoReflect.Descriptor instead.
func (*PullKeyStatesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP(), []int{11}
}

func (x *PullKeyStatesResponse) GetKeyStates() []*KeyStateProto {
	if x != nil {
		return x.KeyStates
	}
	return nil
}

var File_pkg_transport_grpc_transportpb_api_proto protoreflect.FileDescriptor

const file_pkg_transport_grpc_transportpb_api_proto_rawDesc = "" +
	"\n" +
	"(pkg/transport/grpc/transportpb/api.proto\x12\ttransport\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"5\n" +
	"\tRangeList\x12(\n" +
	"\x06ranges\x18\x01 \x03(\v2\x10.transport.RangeR\x06ranges\"\xa0\x01\n" +
	"\n" +
	"GetRequest\x12?\n" +
	"\bversions\x18\x01 \x03(\v2#.transport.GetRequest.VersionsEntryR\bversions\x1aQ\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.transport.RangeListR\x05value:\x028\x01\"'\n" +
	"\vGetResponse\x12\x18\n" +
	"\aupdates\x18\x01 \x03(\fR\aupdates\"*\n" +
	"\x0ePublishRequest\x12\x18\n" +
	"\aupdates\x18\x01 \x03(\fR\aupdates\"\xb2\x01\n" +
	"\x18GetVersionVectorResponse\x12V\n" +
	"\vVectorClock\x18\x01 \x03(\v24.transport.GetVersionVectorResponse.VectorClockEntryR\vVectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\",\n" +
	"\x11RestoreSeqRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\".\n" +
	"\x14GetKeyDigestsRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\rR\x06bucket\"\x9c\x01\n" +
	"\x15GetKeyDigestsResponse\x12G\n" +
	"\adigests\x18\x01 \x03(\v2-.transport.GetKeyDigestsResponse.DigestsEntryR\adigests\x1a:\n" +
	"\fDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"*\n" +
	"\x14PullKeyStatesRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\xea\x02\n" +
	"\rKeyStateProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tcrdt_type\x18\x02 \x01(\tR\bcrdtType\x12\x14\n" +
	"\x05state\x18\x03 \x01(\fR\x05state\x12\x1c\n" +
	"\ttombstone\x18\x04 \x01(\bR\ttombstone\x12-\n" +
	"\x13set_time_stamp_wall\x18\x05 \x01(\x04R\x10setTimeStampWall\x123\n" +
	"\x16set_time_stamp_lamport\x18\x06 \x01(\x04R\x13setTimeStampLamport\x12)\n" +
	"\x11set_time_stamp_id\x18\a \x01(\tR\x0esetTimeStampId\x120\n" +
	"\x02vc\x18\b \x03(\v2 .transport.KeyStateProto.VcEntryR\x02vc\x1a5\n" +
	"\aVcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"P\n" +
	"\x15PullKeyStatesResponse\x127\n" +
	"\n" +
	"key_states\x18\x01 \x03(\v2\x18.transport.KeyStateProtoR\tkeyStates2\xba\x03\n" +
	"\aUpdates\x12<\n" +
	"\aPublish\x12\x19.transport.PublishRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\n" +
	"RestoreSeq\x12\x1c.transport.RestoreSeqRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x03Get\x12\x15.transport.GetRequest\x1a\x16.transport.GetResponse\x12O\n" +
	"\x10GetVersionVector\x12\x16.google.protobuf.Empty\x1a#.transport.GetVersionVectorResponse\x12R\n" +
	"\rGetKeyDigests\x12\x1f.transport.GetKeyDigestsRequest\x1a .transport.GetKeyDigestsResponse\x12R\n" +
	"\rPullKeyStates\x12\x1f.transport.PullKeyStatesRequest\x1a .transport.PullKeyStatesResponseB Z\x1epkg/transport/grpc/transportpbb\x06proto3"

var (
	file_pkg_transport_grpc_transportpb_api_proto_rawDescOnce sync.Once
	file_pkg_transport_grpc_transportpb_api_proto_rawDescData []byte
)

func file_pkg_transport_grpc_transportpb_api_proto_rawDescGZIP() []byte {
	file_pkg_transport_grpc_transportpb_api_proto_rawDescOnce.Do(func() {
		file_pkg_transport_grpc_transportpb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_transport_grpc_transportpb_api_proto_rawDesc), len(file_pkg_transport_grpc_transportpb_api_proto_rawDesc)))
	})
	return file_pkg_transport_grpc_transportpb_api_proto_rawDescData
}

var file_pkg_transport_grpc_transportpb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_transport_grpc_transportpb_api_proto_goTypes = []any{
	(*Range)(nil),                    // 0: transport.Range
	(*RangeList)(nil),                // 1: transport.RangeList
	(*GetRequest)(nil),               // 2: transport.GetRequest
	(*GetResponse)(nil),              // 3: transport.GetResponse
	(*PublishRequest)(nil),           // 4: transport.PublishRequest
	(*GetVersionVectorResponse)(nil), // 5: transport.GetVersionVectorResponse
	(*RestoreSeqRequest)(nil),        // 6: transport.RestoreSeqRequest
	(*GetKeyDigestsRequest)(nil),     // 7: transport.GetKeyDigestsRequest
	(*GetKeyDigestsResponse)(nil),    // 8: transport.GetKeyDigestsResponse
	(*PullKeyStatesRequest)(nil),     // 9: transport.PullKeyStatesRequest
	(*KeyStateProto)(nil),            // 10: transport.KeyStateProto
	(*PullKeyStatesResponse)(nil),    // 11: transport.PullKeyStatesResponse
	nil,                              // 12: transport.GetRequest.VersionsEntry
	nil,                              // 13: transport.GetVersionVectorResponse.VectorClockEntry
	nil,                              // 14: transport.GetKeyDigestsResponse.DigestsEntry
	nil,                              // 15: transport.KeyStateProto.VcEntry
	(*emptypb.Empty)(nil),            // 16: google.protobuf.Empty
}
var file_pkg_transport_grpc_transportpb_api_proto_depIdxs = []int32{
	0,  // 0: transport.RangeList.ranges:type_name -> transport.Range
	12, // 1: transport.GetRequest.versions:type_name -> transport.GetRequest.VersionsEntry
	13, // 2: transport.GetVersionVectorResponse.VectorClock:type_name -> transport.GetVersionVectorResponse.VectorClockEntry
	14, // 3: transport.GetKeyDigestsResponse.digests:type_name -> transport.GetKeyDigestsResponse.DigestsEntry
	15, // 4: transport.KeyStateProto.vc:type_name -> transport.KeyStateProto.VcEntry
	10, // 5: transport.PullKeyStatesResponse.key_states:type_name -> transport.KeyStateProto
	1,  // 6: transport.GetRequest.VersionsEntry.value:type_name -> transport.RangeList
	4,  // 7: transport.Updates.Publish:input_type -> transport.PublishRequest
	6,  // 8: transport.Updates.RestoreSeq:input_type -> transport.RestoreSeqRequest
	2,  // 9: transport.Updates.Get:input_type -> transport.GetRequest
	16, // 10: transport.Updates.GetVersionVector:input_type -> google.protobuf.Empty
	7,  // 11: transport.Updates.GetKeyDigests:input_type -> transport.GetKeyDigestsRequest
	9,  // 12: transport.Updates.PullKeyStates:input_type -> transport.PullKeyStatesRequest
	16, // 13: transport.Updates.Publish:output_type -> google.protobuf.Empty
	16, // 14: transport.Updates.RestoreSeq:output_type -> google.protobuf.Empty
	3,  // 15: transport.Updates.Get:output_type -> transport.GetResponse
	5,  // 16: transport.Updates.GetVersionVector:output_type -> transport.GetVersionVectorResponse
	8,  // 17: transport.Updates.GetKeyDigests:output_type -> transport.GetKeyDigestsResponse
	11, // 18: transport.Updates.PullKeyStates:output_type -> transport.PullKeyStatesResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_transport_grpc_transportpb_api_proto_init() }
func file_pkg_transport_grpc_transportpb_api_proto_init() {
	if File_pkg_transport_grpc_transportpb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_transport_grpc_transportpb_api_proto_rawDesc), len(file_pkg_transport_grpc_transportpb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_transport_grpc_transportpb_api_proto_goTypes,
		DependencyIndexes: file_pkg_transport_grpc_transportpb_api_proto_depIdxs,
		MessageInfos:      file_pkg_transport_grpc_transportpb_api_proto_msgTypes,
	}.Build()
	File_pkg_transport_grpc_transportpb_api_proto = out.File
	file_pkg_transport_grpc_transportpb_api_proto_goTypes = nil
	file_pkg_transport_grpc_transportpb_api_proto_depIdxs = nil
}
