// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pkg/transport/grpc/api.proto

package transportpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Updates_Publish_FullMethodName          = "/transport.Updates/Publish"
	Updates_RestoreSeq_FullMethodName       = "/transport.Updates/RestoreSeq"
	Updates_Get_FullMethodName              = "/transport.Updates/Get"
	Updates_GetVersionVector_FullMethodName = "/transport.Updates/GetVersionVector"
	Updates_GetKeyDigests_FullMethodName    = "/transport.Updates/GetKeyDigests"
	Updates_PullKeyStates_FullMethodName    = "/transport.Updates/PullKeyStates"
)

// UpdatesClient is the client API for Updates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdatesClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestoreSeq(ctx context.Context, in *RestoreSeqRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetVersionVector(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetVersionVectorResponse, error)
	GetKeyDigests(ctx context.Context, in *GetKeyDigestsRequest, opts ...grpc.CallOption) (*GetKeyDigestsResponse, error)
	PullKeyStates(ctx context.Context, in *PullKeyStatesRequest, opts ...grpc.CallOption) (*PullKeyStatesResponse, error)
}

type updatesClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdatesClient(cc grpc.ClientConnInterface) UpdatesClient {
	return &updatesClient{cc}
}

func (c *updatesClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Updates_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updatesClient) RestoreSeq(ctx context.Context, in *RestoreSeqRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Updates_RestoreSeq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updatesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Updates_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updatesClient) GetVersionVector(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetVersionVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionVectorResponse)
	err := c.cc.Invoke(ctx, Updates_GetVersionVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updatesClient) GetKeyDigests(ctx context.Context, in *GetKeyDigestsRequest, opts ...grpc.CallOption) (*GetKeyDigestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyDigestsResponse)
	err := c.cc.Invoke(ctx, Updates_GetKeyDigests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updatesClient) PullKeyStates(ctx context.Context, in *PullKeyStatesRequest, opts ...grpc.CallOption) (*PullKeyStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullKeyStatesResponse)
	err := c.cc.Invoke(ctx, Updates_PullKeyStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdatesServer is the server API for Updates service.
// All implementations must embed UnimplementedUpdatesServer
// for forward compatibility.
type UpdatesServer interface {
	Publish(context.Context, *PublishRequest) (*emptypb.Empty, error)
	RestoreSeq(context.Context, *RestoreSeqRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetVersionVector(context.Context, *emptypb.Empty) (*GetVersionVectorResponse, error)
	GetKeyDigests(context.Context, *GetKeyDigestsRequest) (*GetKeyDigestsResponse, error)
	PullKeyStates(context.Context, *PullKeyStatesRequest) (*PullKeyStatesResponse, error)
	mustEmbedUnimplementedUpdatesServer()
}

// UnimplementedUpdatesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdatesServer struct{}

func (UnimplementedUpdatesServer) Publish(context.Context, *PublishRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedUpdatesServer) RestoreSeq(context.Context, *RestoreSeqRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSeq not implemented")
}
func (UnimplementedUpdatesServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUpdatesServer) GetVersionVector(context.Context, *emptypb.Empty) (*GetVersionVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersionVector not implemented")
}
func (UnimplementedUpdatesServer) GetKeyDigests(context.Context, *GetKeyDigestsRequest) (*GetKeyDigestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyDigests not implemented")
}
func (UnimplementedUpdatesServer) PullKeyStates(context.Context, *PullKeyStatesRequest) (*PullKeyStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullKeyStates not implemented")
}
func (UnimplementedUpdatesServer) mustEmbedUnimplementedUpdatesServer() {}
func (UnimplementedUpdatesServer) testEmbeddedByValue()                 {}

// UnsafeUpdatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdatesServer will
// result in compilation errors.
type UnsafeUpdatesServer interface {
	mustEmbedUnimplementedUpdatesServer()
}

func RegisterUpdatesServer(s grpc.ServiceRegistrar, srv UpdatesServer) {
	// If the following call panics, it indicates UnimplementedUpdatesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Updates_ServiceDesc, srv)
}

func _Updates_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatesServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Updates_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatesServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Updates_RestoreSeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSeqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatesServer).RestoreSeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Updates_RestoreSeq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatesServer).RestoreSeq(ctx, req.(*RestoreSeqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Updates_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Updates_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Updates_GetVersionVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatesServer).GetVersionVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Updates_GetVersionVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatesServer).GetVersionVector(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Updates_GetKeyDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyDigestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatesServer).GetKeyDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Updates_GetKeyDigests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatesServer).GetKeyDigests(ctx, req.(*GetKeyDigestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Updates_PullKeyStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullKeyStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatesServer).PullKeyStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Updates_PullKeyStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatesServer).PullKeyStates(ctx, req.(*PullKeyStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Updates_ServiceDesc is the grpc.ServiceDesc for Updates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Updates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transport.Updates",
	HandlerType: (*UpdatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Updates_Publish_Handler,
		},
		{
			MethodName: "RestoreSeq",
			Handler:    _Updates_RestoreSeq_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Updates_Get_Handler,
		},
		{
			MethodName: "GetVersionVector",
			Handler:    _Updates_GetVersionVector_Handler,
		},
		{
			MethodName: "GetKeyDigests",
			Handler:    _Updates_GetKeyDigests_Handler,
		},
		{
			MethodName: "PullKeyStates",
			Handler:    _Updates_PullKeyStates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/transport/grpc/api.proto",
}
