// Code generated by MockGen. DO NOT EDIT.
// Source: engine.go
//
// Generated by this command:
//
//	mockgen -source=engine.go -destination=mocks/engine.mock.go Engine
//

// Package mock_engine is a generated GoMock package.
package mock_engine

import (
	context "context"
	crdt "github.com/kestfor/in-memorydb/pkg/crdt"
	hlc "github.com/kestfor/in-memorydb/pkg/crdt/hlc"
	engine "github.com/kestfor/in-memorydb/pkg/storage/engine"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
	isgomock struct{}
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// Clock mocks base method.
func (m *MockEngine) Clock() *hlc.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clock")
	ret0, _ := ret[0].(*hlc.Time)
	return ret0
}

// Clock indicates an expected call of Clock.
func (mr *MockEngineMockRecorder) Clock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clock", reflect.TypeOf((*MockEngine)(nil).Clock))
}

// Delete mocks base method.
func (m *MockEngine) Delete(ctx context.Context, key string) (*engine.CRDTEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(*engine.CRDTEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockEngineMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEngine)(nil).Delete), ctx, key)
}

// DeleteWithTimeStamp mocks base method.
func (m *MockEngine) DeleteWithTimeStamp(ctx context.Context, ts *hlc.Timestamp, key string) (*engine.CRDTEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeStamp", ctx, ts, key)
	ret0, _ := ret[0].(*engine.CRDTEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DeleteWithTimeStamp indicates an expected call of DeleteWithTimeStamp.
func (mr *MockEngineMockRecorder) DeleteWithTimeStamp(ctx, ts, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeStamp", reflect.TypeOf((*MockEngine)(nil).DeleteWithTimeStamp), ctx, ts, key)
}

// Get mocks base method.
func (m *MockEngine) Get(ctx context.Context, key string) (*engine.CRDTEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*engine.CRDTEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEngineMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEngine)(nil).Get), ctx, key)
}

// GetOrCreate mocks base method.
func (m *MockEngine) GetOrCreate(ctx context.Context, key string, createFunc engine.CreateFunc) (*engine.CRDTEntry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, key, createFunc)
	ret0, _ := ret[0].(*engine.CRDTEntry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockEngineMockRecorder) GetOrCreate(ctx, key, createFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockEngine)(nil).GetOrCreate), ctx, key, createFunc)
}

// Put mocks base method.
func (m *MockEngine) Put(ctx context.Context, key string, obj crdt.CRDT, callback engine.Callback) *hlc.Timestamp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, obj, callback)
	ret0, _ := ret[0].(*hlc.Timestamp)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockEngineMockRecorder) Put(ctx, key, obj, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockEngine)(nil).Put), ctx, key, obj, callback)
}

// PutWithTimeStamp mocks base method.
func (m *MockEngine) PutWithTimeStamp(ctx context.Context, ts *hlc.Timestamp, key string, obj crdt.CRDT, callback engine.Callback) *hlc.Timestamp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutWithTimeStamp", ctx, ts, key, obj, callback)
	ret0, _ := ret[0].(*hlc.Timestamp)
	return ret0
}

// PutWithTimeStamp indicates an expected call of PutWithTimeStamp.
func (mr *MockEngineMockRecorder) PutWithTimeStamp(ctx, ts, key, obj, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutWithTimeStamp", reflect.TypeOf((*MockEngine)(nil).PutWithTimeStamp), ctx, ts, key, obj, callback)
}

// Start mocks base method.
func (m *MockEngine) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockEngineMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEngine)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockEngine) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockEngineMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEngine)(nil).Stop))
}

// Update mocks base method.
func (m *MockEngine) Update(ctx context.Context, key string, updateFunc engine.UpdateFunc) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, key, updateFunc)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEngineMockRecorder) Update(ctx, key, updateFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEngine)(nil).Update), ctx, key, updateFunc)
}
