// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package crdt

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// CRDTTypePNCounter is a CRDTType of type PNCounter.
	CRDTTypePNCounter CRDTType = "PNCounter"
	// CRDTTypeLWWHLCRegister is a CRDTType of type LWWHLCRegister.
	CRDTTypeLWWHLCRegister CRDTType = "LWWHLCRegister"
)

var ErrInvalidCRDTType = errors.New("not a valid CRDTType")

// String implements the Stringer interface.
func (x CRDTType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CRDTType) IsValid() bool {
	_, err := ParseCRDTType(string(x))
	return err == nil
}

var _CRDTTypeValue = map[string]CRDTType{
	"PNCounter":      CRDTTypePNCounter,
	"pncounter":      CRDTTypePNCounter,
	"LWWHLCRegister": CRDTTypeLWWHLCRegister,
	"lwwhlcregister": CRDTTypeLWWHLCRegister,
}

// ParseCRDTType attempts to convert a string to a CRDTType.
func ParseCRDTType(name string) (CRDTType, error) {
	if x, ok := _CRDTTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _CRDTTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return CRDTType(""), fmt.Errorf("%s is %w", name, ErrInvalidCRDTType)
}

// MarshalText implements the text marshaller method.
func (x CRDTType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CRDTType) UnmarshalText(text []byte) error {
	tmp, err := ParseCRDTType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *CRDTType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
