// Code generated by MockGen. DO NOT EDIT.
// Source: version_manager.go
//
// Generated by this command:
//
//	mockgen -source=version_manager.go -destination=mocks/version_manager.mock.go VersionManager
//

// Package mock_version_manager is a generated GoMock package.
package mock_version_manager

import (
	context "context"
	wal "github.com/kestfor/in-memorydb/pkg/storage/wal"
	structs "github.com/kestfor/in-memorydb/pkg/structs"
	types "github.com/kestfor/in-memorydb/pkg/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVersionManager is a mock of VersionManager interface.
type MockVersionManager struct {
	ctrl     *gomock.Controller
	recorder *MockVersionManagerMockRecorder
	isgomock struct{}
}

// MockVersionManagerMockRecorder is the mock recorder for MockVersionManager.
type MockVersionManagerMockRecorder struct {
	mock *MockVersionManager
}

// NewMockVersionManager creates a new mock instance.
func NewMockVersionManager(ctrl *gomock.Controller) *MockVersionManager {
	mock := &MockVersionManager{ctrl: ctrl}
	mock.recorder = &MockVersionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionManager) EXPECT() *MockVersionManagerMockRecorder {
	return m.recorder
}

// Advance mocks base method.
func (m *MockVersionManager) Advance() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Advance")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Advance indicates an expected call of Advance.
func (mr *MockVersionManagerMockRecorder) Advance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Advance", reflect.TypeOf((*MockVersionManager)(nil).Advance))
}

// RestoreFromWal mocks base method.
func (m *MockVersionManager) RestoreFromWal(ctx context.Context, arg1 wal.WAL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreFromWal", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreFromWal indicates an expected call of RestoreFromWal.
func (mr *MockVersionManagerMockRecorder) RestoreFromWal(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreFromWal", reflect.TypeOf((*MockVersionManager)(nil).RestoreFromWal), ctx, arg1)
}

// Update mocks base method.
func (m *MockVersionManager) Update(ctx context.Context, updates ...*types.Update) []*types.Update {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range updates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].([]*types.Update)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVersionManagerMockRecorder) Update(ctx any, updates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, updates...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVersionManager)(nil).Update), varargs...)
}

// VectorClockContiguous mocks base method.
func (m *MockVersionManager) VectorClockContiguous() types.VectorClock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VectorClockContiguous")
	ret0, _ := ret[0].(types.VectorClock)
	return ret0
}

// VectorClockContiguous indicates an expected call of VectorClockContiguous.
func (mr *MockVersionManagerMockRecorder) VectorClockContiguous() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VectorClockContiguous", reflect.TypeOf((*MockVersionManager)(nil).VectorClockContiguous))
}

// VectorClockMax mocks base method.
func (m *MockVersionManager) VectorClockMax() types.VectorClock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VectorClockMax")
	ret0, _ := ret[0].(types.VectorClock)
	return ret0
}

// VectorClockMax indicates an expected call of VectorClockMax.
func (mr *MockVersionManagerMockRecorder) VectorClockMax() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VectorClockMax", reflect.TypeOf((*MockVersionManager)(nil).VectorClockMax))
}

// VersionDiff mocks base method.
func (m *MockVersionManager) VersionDiff(remote types.VectorClock) map[string][]structs.Range {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VersionDiff", remote)
	ret0, _ := ret[0].(map[string][]structs.Range)
	return ret0
}

// VersionDiff indicates an expected call of VersionDiff.
func (mr *MockVersionManagerMockRecorder) VersionDiff(remote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VersionDiff", reflect.TypeOf((*MockVersionManager)(nil).VersionDiff), remote)
}
