// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/lume.proto

package lume

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lume_Set_FullMethodName    = "/api.Lume/Set"
	Lume_Get_FullMethodName    = "/api.Lume/Get"
	Lume_Delete_FullMethodName = "/api.Lume/Delete"
	Lume_Apply_FullMethodName  = "/api.Lume/Apply"
)

// LumeClient is the client API for Lume service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LumeClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type lumeClient struct {
	cc grpc.ClientConnInterface
}

func NewLumeClient(cc grpc.ClientConnInterface) LumeClient {
	return &lumeClient{cc}
}

func (c *lumeClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Lume_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Lume_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumeClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Lume_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumeClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Lume_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LumeServer is the server API for Lume service.
// All implementations must embed UnimplementedLumeServer
// for forward compatibility.
type LumeServer interface {
	Set(context.Context, *SetRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Apply(context.Context, *ApplyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLumeServer()
}

// UnimplementedLumeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLumeServer struct{}

func (UnimplementedLumeServer) Set(context.Context, *SetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedLumeServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLumeServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLumeServer) Apply(context.Context, *ApplyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedLumeServer) mustEmbedUnimplementedLumeServer() {}
func (UnimplementedLumeServer) testEmbeddedByValue()              {}

// UnsafeLumeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LumeServer will
// result in compilation errors.
type UnsafeLumeServer interface {
	mustEmbedUnimplementedLumeServer()
}

func RegisterLumeServer(s grpc.ServiceRegistrar, srv LumeServer) {
	// If the following call panics, it indicates UnimplementedLumeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lume_ServiceDesc, srv)
}

func _Lume_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumeServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lume_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumeServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lume_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lume_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lume_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lume_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumeServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lume_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumeServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lume_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumeServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lume_ServiceDesc is the grpc.ServiceDesc for Lume service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lume_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Lume",
	HandlerType: (*LumeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Lume_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Lume_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Lume_Delete_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Lume_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/lume.proto",
}

const (
	LumeStreaming_Get_FullMethodName    = "/api.LumeStreaming/Get"
	LumeStreaming_Apply_FullMethodName  = "/api.LumeStreaming/Apply"
	LumeStreaming_Delete_FullMethodName = "/api.LumeStreaming/Delete"
	LumeStreaming_Set_FullMethodName    = "/api.LumeStreaming/Set"
)

// LumeStreamingClient is the client API for LumeStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LumeStreamingClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	Apply(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ApplyRequest, emptypb.Empty], error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeleteResponse], error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[emptypb.Empty], error)
}

type lumeStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewLumeStreamingClient(cc grpc.ClientConnInterface) LumeStreamingClient {
	return &lumeStreamingClient{cc}
}

func (c *lumeStreamingClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LumeStreaming_ServiceDesc.Streams[0], LumeStreaming_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *lumeStreamingClient) Apply(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ApplyRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LumeStreaming_ServiceDesc.Streams[1], LumeStreaming_Apply_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplyRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_ApplyClient = grpc.BidiStreamingClient[ApplyRequest, emptypb.Empty]

func (c *lumeStreamingClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeleteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LumeStreaming_ServiceDesc.Streams[2], LumeStreaming_Delete_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeleteRequest, DeleteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_DeleteClient = grpc.ServerStreamingClient[DeleteResponse]

func (c *lumeStreamingClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LumeStreaming_ServiceDesc.Streams[3], LumeStreaming_Set_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetRequest, emptypb.Empty]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_SetClient = grpc.ServerStreamingClient[emptypb.Empty]

// LumeStreamingServer is the server API for LumeStreaming service.
// All implementations must embed UnimplementedLumeStreamingServer
// for forward compatibility.
type LumeStreamingServer interface {
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	Apply(grpc.BidiStreamingServer[ApplyRequest, emptypb.Empty]) error
	Delete(*DeleteRequest, grpc.ServerStreamingServer[DeleteResponse]) error
	Set(*SetRequest, grpc.ServerStreamingServer[emptypb.Empty]) error
	mustEmbedUnimplementedLumeStreamingServer()
}

// UnimplementedLumeStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLumeStreamingServer struct{}

func (UnimplementedLumeStreamingServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLumeStreamingServer) Apply(grpc.BidiStreamingServer[ApplyRequest, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedLumeStreamingServer) Delete(*DeleteRequest, grpc.ServerStreamingServer[DeleteResponse]) error {
	return status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLumeStreamingServer) Set(*SetRequest, grpc.ServerStreamingServer[emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedLumeStreamingServer) mustEmbedUnimplementedLumeStreamingServer() {}
func (UnimplementedLumeStreamingServer) testEmbeddedByValue()                       {}

// UnsafeLumeStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LumeStreamingServer will
// result in compilation errors.
type UnsafeLumeStreamingServer interface {
	mustEmbedUnimplementedLumeStreamingServer()
}

func RegisterLumeStreamingServer(s grpc.ServiceRegistrar, srv LumeStreamingServer) {
	// If the following call panics, it indicates UnimplementedLumeStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LumeStreaming_ServiceDesc, srv)
}

func _LumeStreaming_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LumeStreamingServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_GetServer = grpc.ServerStreamingServer[GetResponse]

func _LumeStreaming_Apply_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LumeStreamingServer).Apply(&grpc.GenericServerStream[ApplyRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_ApplyServer = grpc.BidiStreamingServer[ApplyRequest, emptypb.Empty]

func _LumeStreaming_Delete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeleteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LumeStreamingServer).Delete(m, &grpc.GenericServerStream[DeleteRequest, DeleteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_DeleteServer = grpc.ServerStreamingServer[DeleteResponse]

func _LumeStreaming_Set_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LumeStreamingServer).Set(m, &grpc.GenericServerStream[SetRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumeStreaming_SetServer = grpc.ServerStreamingServer[emptypb.Empty]

// LumeStreaming_ServiceDesc is the grpc.ServiceDesc for LumeStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LumeStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LumeStreaming",
	HandlerType: (*LumeStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _LumeStreaming_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Apply",
			Handler:       _LumeStreaming_Apply_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Delete",
			Handler:       _LumeStreaming_Delete_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Set",
			Handler:       _LumeStreaming_Set_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/lume.proto",
}
