// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/lume.proto

package lume

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_NOT_SPECIFIED Type = 0
	Type_TYPE_PN_COUNTER    Type = 1
	Type_TYPE_LWW_REGISTER  Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_NOT_SPECIFIED",
		1: "TYPE_PN_COUNTER",
		2: "TYPE_LWW_REGISTER",
	}
	Type_value = map[string]int32{
		"TYPE_NOT_SPECIFIED": 0,
		"TYPE_PN_COUNTER":    1,
		"TYPE_LWW_REGISTER":  2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_lume_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_api_lume_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{0}
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CrdtType      Type                   `protobuf:"varint,2,opt,name=crdt_type,json=crdtType,proto3,enum=api.Type" json:"crdt_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_lume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetCrdtType() Type {
	if x != nil {
		return x.CrdtType
	}
	return Type_TYPE_NOT_SPECIFIED
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_lume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_lume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_lume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CrdtType Type                   `protobuf:"varint,1,opt,name=crdt_type,json=crdtType,proto3,enum=api.Type" json:"crdt_type,omitempty"`
	Ok       bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"` // key present
	// Types that are valid to be assigned to Data:
	//
	//	*GetResponse_CounterData
	//	*GetResponse_RegisterData
	Data          isGetResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_lume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetCrdtType() Type {
	if x != nil {
		return x.CrdtType
	}
	return Type_TYPE_NOT_SPECIFIED
}

func (x *GetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetResponse) GetData() isGetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetResponse) GetCounterData() *GetResponse_Counter {
	if x != nil {
		if x, ok := x.Data.(*GetResponse_CounterData); ok {
			return x.CounterData
		}
	}
	return nil
}

func (x *GetResponse) GetRegisterData() *GetResponse_Register {
	if x != nil {
		if x, ok := x.Data.(*GetResponse_RegisterData); ok {
			return x.RegisterData
		}
	}
	return nil
}

type isGetResponse_Data interface {
	isGetResponse_Data()
}

type GetResponse_CounterData struct {
	CounterData *GetResponse_Counter `protobuf:"bytes,3,opt,name=counter_data,json=counterData,proto3,oneof"`
}

type GetResponse_RegisterData struct {
	RegisterData *GetResponse_Register `protobuf:"bytes,4,opt,name=register_data,json=registerData,proto3,oneof"`
}

func (*GetResponse_CounterData) isGetResponse_Data() {}

func (*GetResponse_RegisterData) isGetResponse_Data() {}

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*ApplyRequest_RegisterOperation
	//	*ApplyRequest_CounterOperationInc
	//	*ApplyRequest_CounterOperationDec
	Operation     isApplyRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_api_lume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApplyRequest) GetOperation() isApplyRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ApplyRequest) GetRegisterOperation() *ApplyRequest_Register {
	if x != nil {
		if x, ok := x.Operation.(*ApplyRequest_RegisterOperation); ok {
			return x.RegisterOperation
		}
	}
	return nil
}

func (x *ApplyRequest) GetCounterOperationInc() *ApplyRequest_CounterInc {
	if x != nil {
		if x, ok := x.Operation.(*ApplyRequest_CounterOperationInc); ok {
			return x.CounterOperationInc
		}
	}
	return nil
}

func (x *ApplyRequest) GetCounterOperationDec() *ApplyRequest_CounterDec {
	if x != nil {
		if x, ok := x.Operation.(*ApplyRequest_CounterOperationDec); ok {
			return x.CounterOperationDec
		}
	}
	return nil
}

type isApplyRequest_Operation interface {
	isApplyRequest_Operation()
}

type ApplyRequest_RegisterOperation struct {
	RegisterOperation *ApplyRequest_Register `protobuf:"bytes,2,opt,name=register_operation,json=registerOperation,proto3,oneof"`
}

type ApplyRequest_CounterOperationInc struct {
	CounterOperationInc *ApplyRequest_CounterInc `protobuf:"bytes,3,opt,name=counter_operation_inc,json=counterOperationInc,proto3,oneof"`
}

type ApplyRequest_CounterOperationDec struct {
	CounterOperationDec *ApplyRequest_CounterDec `protobuf:"bytes,4,opt,name=counter_operation_dec,json=counterOperationDec,proto3,oneof"`
}

func (*ApplyRequest_RegisterOperation) isApplyRequest_Operation() {}

func (*ApplyRequest_CounterOperationInc) isApplyRequest_Operation() {}

func (*ApplyRequest_CounterOperationDec) isApplyRequest_Operation() {}

type GetResponse_Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse_Counter) Reset() {
	*x = GetResponse_Counter{}
	mi := &file_api_lume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse_Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Counter) ProtoMessage() {}

func (x *GetResponse_Counter) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Counter.ProtoReflect.Descriptor instead.
func (*GetResponse_Counter) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetResponse_Counter) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type GetResponse_Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []byte                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse_Register) Reset() {
	*x = GetResponse_Register{}
	mi := &file_api_lume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Register) ProtoMessage() {}

func (x *GetResponse_Register) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Register.ProtoReflect.Descriptor instead.
func (*GetResponse_Register) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetResponse_Register) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

type ApplyRequest_Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest_Register) Reset() {
	*x = ApplyRequest_Register{}
	mi := &file_api_lume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest_Register) ProtoMessage() {}

func (x *ApplyRequest_Register) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest_Register.ProtoReflect.Descriptor instead.
func (*ApplyRequest_Register) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ApplyRequest_Register) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ApplyRequest_CounterInc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest_CounterInc) Reset() {
	*x = ApplyRequest_CounterInc{}
	mi := &file_api_lume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest_CounterInc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest_CounterInc) ProtoMessage() {}

func (x *ApplyRequest_CounterInc) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest_CounterInc.ProtoReflect.Descriptor instead.
func (*ApplyRequest_CounterInc) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ApplyRequest_CounterInc) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type ApplyRequest_CounterDec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           int64                  `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest_CounterDec) Reset() {
	*x = ApplyRequest_CounterDec{}
	mi := &file_api_lume_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest_CounterDec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest_CounterDec) ProtoMessage() {}

func (x *ApplyRequest_CounterDec) ProtoReflect() protoreflect.Message {
	mi := &file_api_lume_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest_CounterDec.ProtoReflect.Descriptor instead.
func (*ApplyRequest_CounterDec) Descriptor() ([]byte, []int) {
	return file_api_lume_proto_rawDescGZIP(), []int{5, 2}
}

func (x *ApplyRequest_CounterDec) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

var File_api_lume_proto protoreflect.FileDescriptor

const file_api_lume_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/lume.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\tcrdt_type\x18\x02 \x01(\x0e2\t.api.TypeR\bcrdtType\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x89\x02\n" +
	"\vGetResponse\x12&\n" +
	"\tcrdt_type\x18\x01 \x01(\x0e2\t.api.TypeR\bcrdtType\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12=\n" +
	"\fcounter_data\x18\x03 \x01(\v2\x18.api.GetResponse.CounterH\x00R\vcounterData\x12@\n" +
	"\rregister_data\x18\x04 \x01(\v2\x19.api.GetResponse.RegisterH\x00R\fregisterData\x1a\x1b\n" +
	"\aCounter\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x03R\x03val\x1a\x1c\n" +
	"\bRegister\x12\x10\n" +
	"\x03val\x18\x01 \x01(\fR\x03valB\x06\n" +
	"\x04data\"\x84\x03\n" +
	"\fApplyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12K\n" +
	"\x12register_operation\x18\x02 \x01(\v2\x1a.api.ApplyRequest.RegisterH\x00R\x11registerOperation\x12R\n" +
	"\x15counter_operation_inc\x18\x03 \x01(\v2\x1c.api.ApplyRequest.CounterIncH\x00R\x13counterOperationInc\x12R\n" +
	"\x15counter_operation_dec\x18\x04 \x01(\v2\x1c.api.ApplyRequest.CounterDecH\x00R\x13counterOperationDec\x1a \n" +
	"\bRegister\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x1a\x1e\n" +
	"\n" +
	"CounterInc\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x03R\x03val\x1a\x1e\n" +
	"\n" +
	"CounterDec\x12\x10\n" +
	"\x03val\x18\x01 \x01(\x03R\x03valB\v\n" +
	"\toperation*J\n" +
	"\x04Type\x12\x16\n" +
	"\x12TYPE_NOT_SPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTYPE_PN_COUNTER\x10\x01\x12\x15\n" +
	"\x11TYPE_LWW_REGISTER\x10\x022\xc7\x01\n" +
	"\x04Lume\x12.\n" +
	"\x03Set\x12\x0f.api.SetRequest\x1a\x16.google.protobuf.Empty\x12(\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x10.api.GetResponse\x121\n" +
	"\x06Delete\x12\x12.api.DeleteRequest\x1a\x13.api.DeleteResponse\x122\n" +
	"\x05Apply\x12\x11.api.ApplyRequest\x1a\x16.google.protobuf.Empty2\xda\x01\n" +
	"\rLumeStreaming\x12*\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x10.api.GetResponse0\x01\x126\n" +
	"\x05Apply\x12\x11.api.ApplyRequest\x1a\x16.google.protobuf.Empty(\x010\x01\x123\n" +
	"\x06Delete\x12\x12.api.DeleteRequest\x1a\x13.api.DeleteResponse0\x01\x120\n" +
	"\x03Set\x12\x0f.api.SetRequest\x1a\x16.google.protobuf.Empty0\x01BL\n" +
	"\acom.apiB\tLumeProtoP\x01Z\n" +
	"api/lumepb\xa2\x02\x03AXX\xaa\x02\x03Api\xca\x02\x03Api\xe2\x02\x0fApi\\GPBMetadata\xea\x02\x03Apib\x06proto3"

var (
	file_api_lume_proto_rawDescOnce sync.Once
	file_api_lume_proto_rawDescData []byte
)

func file_api_lume_proto_rawDescGZIP() []byte {
	file_api_lume_proto_rawDescOnce.Do(func() {
		file_api_lume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lume_proto_rawDesc), len(file_api_lume_proto_rawDesc)))
	})
	return file_api_lume_proto_rawDescData
}

var file_api_lume_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_lume_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_lume_proto_goTypes = []any{
	(Type)(0),                       // 0: api.Type
	(*SetRequest)(nil),              // 1: api.SetRequest
	(*DeleteRequest)(nil),           // 2: api.DeleteRequest
	(*DeleteResponse)(nil),          // 3: api.DeleteResponse
	(*GetRequest)(nil),              // 4: api.GetRequest
	(*GetResponse)(nil),             // 5: api.GetResponse
	(*ApplyRequest)(nil),            // 6: api.ApplyRequest
	(*GetResponse_Counter)(nil),     // 7: api.GetResponse.Counter
	(*GetResponse_Register)(nil),    // 8: api.GetResponse.Register
	(*ApplyRequest_Register)(nil),   // 9: api.ApplyRequest.Register
	(*ApplyRequest_CounterInc)(nil), // 10: api.ApplyRequest.CounterInc
	(*ApplyRequest_CounterDec)(nil), // 11: api.ApplyRequest.CounterDec
	(*emptypb.Empty)(nil),           // 12: google.protobuf.Empty
}
var file_api_lume_proto_depIdxs = []int32{
	0,  // 0: api.SetRequest.crdt_type:type_name -> api.Type
	0,  // 1: api.GetResponse.crdt_type:type_name -> api.Type
	7,  // 2: api.GetResponse.counter_data:type_name -> api.GetResponse.Counter
	8,  // 3: api.GetResponse.register_data:type_name -> api.GetResponse.Register
	9,  // 4: api.ApplyRequest.register_operation:type_name -> api.ApplyRequest.Register
	10, // 5: api.ApplyRequest.counter_operation_inc:type_name -> api.ApplyRequest.CounterInc
	11, // 6: api.ApplyRequest.counter_operation_dec:type_name -> api.ApplyRequest.CounterDec
	1,  // 7: api.Lume.Set:input_type -> api.SetRequest
	4,  // 8: api.Lume.Get:input_type -> api.GetRequest
	2,  // 9: api.Lume.Delete:input_type -> api.DeleteRequest
	6,  // 10: api.Lume.Apply:input_type -> api.ApplyRequest
	4,  // 11: api.LumeStreaming.Get:input_type -> api.GetRequest
	6,  // 12: api.LumeStreaming.Apply:input_type -> api.ApplyRequest
	2,  // 13: api.LumeStreaming.Delete:input_type -> api.DeleteRequest
	1,  // 14: api.LumeStreaming.Set:input_type -> api.SetRequest
	12, // 15: api.Lume.Set:output_type -> google.protobuf.Empty
	5,  // 16: api.Lume.Get:output_type -> api.GetResponse
	3,  // 17: api.Lume.Delete:output_type -> api.DeleteResponse
	12, // 18: api.Lume.Apply:output_type -> google.protobuf.Empty
	5,  // 19: api.LumeStreaming.Get:output_type -> api.GetResponse
	12, // 20: api.LumeStreaming.Apply:output_type -> google.protobuf.Empty
	3,  // 21: api.LumeStreaming.Delete:output_type -> api.DeleteResponse
	12, // 22: api.LumeStreaming.Set:output_type -> google.protobuf.Empty
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_lume_proto_init() }
func file_api_lume_proto_init() {
	if File_api_lume_proto != nil {
		return
	}
	file_api_lume_proto_msgTypes[4].OneofWrappers = []any{
		(*GetResponse_CounterData)(nil),
		(*GetResponse_RegisterData)(nil),
	}
	file_api_lume_proto_msgTypes[5].OneofWrappers = []any{
		(*ApplyRequest_RegisterOperation)(nil),
		(*ApplyRequest_CounterOperationInc)(nil),
		(*ApplyRequest_CounterOperationDec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lume_proto_rawDesc), len(file_api_lume_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_lume_proto_goTypes,
		DependencyIndexes: file_api_lume_proto_depIdxs,
		EnumInfos:         file_api_lume_proto_enumTypes,
		MessageInfos:      file_api_lume_proto_msgTypes,
	}.Build()
	File_api_lume_proto = out.File
	file_api_lume_proto_goTypes = nil
	file_api_lume_proto_depIdxs = nil
}
