node:
  id: "node1"
  bind_address: "127.0.0.1"
  port: 50051
seeds:
  - "127.0.0.2"
gossip:
  bind_address: "127.0.0.1"
  port: 50052
  fanout: 3
  interval: 30000
  retries: 2
membership:
  port: 50053
persistence:
  wal:
    path: ./wal_data_1
    segment_threshold: 1000
trace:
  enable: false
