// Code generated by MockGen. DO NOT EDIT.
// Source: crdt.go
//
// Generated by this command:
//
//	mockgen -source=crdt.go -destination=mocks/crdt.mock.go CRDT,Delta
//

// Package mock_crdt is a generated GoMock package.
package mock_crdt

import (
	crdt "in-memorydb/pkg/crdt"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCRDTFabric is a mock of CRDTFabric interface.
type MockCRDTFabric struct {
	ctrl     *gomock.Controller
	recorder *MockCRDTFabricMockRecorder
	isgomock struct{}
}

// MockCRDTFabricMockRecorder is the mock recorder for MockCRDTFabric.
type MockCRDTFabricMockRecorder struct {
	mock *MockCRDTFabric
}

// NewMockCRDTFabric creates a new mock instance.
func NewMockCRDTFabric(ctrl *gomock.Controller) *MockCRDTFabric {
	mock := &MockCRDTFabric{ctrl: ctrl}
	mock.recorder = &MockCRDTFabricMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCRDTFabric) EXPECT() *MockCRDTFabricMockRecorder {
	return m.recorder
}

// DeltaFromBytes mocks base method.
func (m *MockCRDTFabric) DeltaFromBytes(crdtType crdt.CRDTType, bytes []byte) (crdt.Delta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeltaFromBytes", crdtType, bytes)
	ret0, _ := ret[0].(crdt.Delta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeltaFromBytes indicates an expected call of DeltaFromBytes.
func (mr *MockCRDTFabricMockRecorder) DeltaFromBytes(crdtType, bytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeltaFromBytes", reflect.TypeOf((*MockCRDTFabric)(nil).DeltaFromBytes), crdtType, bytes)
}

// New mocks base method.
func (m *MockCRDTFabric) New(crdtType crdt.CRDTType, id string) (crdt.CRDT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", crdtType, id)
	ret0, _ := ret[0].(crdt.CRDT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockCRDTFabricMockRecorder) New(crdtType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockCRDTFabric)(nil).New), crdtType, id)
}

// NilDelta mocks base method.
func (m *MockCRDTFabric) NilDelta(crdtType crdt.CRDTType) (crdt.Delta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NilDelta", crdtType)
	ret0, _ := ret[0].(crdt.Delta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NilDelta indicates an expected call of NilDelta.
func (mr *MockCRDTFabricMockRecorder) NilDelta(crdtType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NilDelta", reflect.TypeOf((*MockCRDTFabric)(nil).NilDelta), crdtType)
}

// MockCRDT is a mock of CRDT interface.
type MockCRDT struct {
	ctrl     *gomock.Controller
	recorder *MockCRDTMockRecorder
	isgomock struct{}
}

// MockCRDTMockRecorder is the mock recorder for MockCRDT.
type MockCRDTMockRecorder struct {
	mock *MockCRDT
}

// NewMockCRDT creates a new mock instance.
func NewMockCRDT(ctrl *gomock.Controller) *MockCRDT {
	mock := &MockCRDT{ctrl: ctrl}
	mock.recorder = &MockCRDTMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCRDT) EXPECT() *MockCRDTMockRecorder {
	return m.recorder
}

// ApplyDelta mocks base method.
func (m *MockCRDT) ApplyDelta(delta crdt.Delta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDelta", delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDelta indicates an expected call of ApplyDelta.
func (mr *MockCRDTMockRecorder) ApplyDelta(delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDelta", reflect.TypeOf((*MockCRDT)(nil).ApplyDelta), delta)
}

// MarshalJSON mocks base method.
func (m *MockCRDT) MarshalJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalJSON indicates an expected call of MarshalJSON.
func (mr *MockCRDTMockRecorder) MarshalJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalJSON", reflect.TypeOf((*MockCRDT)(nil).MarshalJSON))
}

// Merge mocks base method.
func (m *MockCRDT) Merge(other crdt.CRDT) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", other)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockCRDTMockRecorder) Merge(other any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockCRDT)(nil).Merge), other)
}

// Type mocks base method.
func (m *MockCRDT) Type() crdt.CRDTType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(crdt.CRDTType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockCRDTMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockCRDT)(nil).Type))
}

// UnmarshalJSON mocks base method.
func (m *MockCRDT) UnmarshalJSON(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalJSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalJSON indicates an expected call of UnmarshalJSON.
func (mr *MockCRDTMockRecorder) UnmarshalJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalJSON", reflect.TypeOf((*MockCRDT)(nil).UnmarshalJSON), data)
}

// Value mocks base method.
func (m *MockCRDT) Value() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockCRDTMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockCRDT)(nil).Value))
}

// MockDelta is a mock of Delta interface.
type MockDelta struct {
	ctrl     *gomock.Controller
	recorder *MockDeltaMockRecorder
	isgomock struct{}
}

// MockDeltaMockRecorder is the mock recorder for MockDelta.
type MockDeltaMockRecorder struct {
	mock *MockDelta
}

// NewMockDelta creates a new mock instance.
func NewMockDelta(ctrl *gomock.Controller) *MockDelta {
	mock := &MockDelta{ctrl: ctrl}
	mock.recorder = &MockDeltaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelta) EXPECT() *MockDeltaMockRecorder {
	return m.recorder
}

// CreateCRDT mocks base method.
func (m *MockDelta) CreateCRDT() (crdt.CRDT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCRDT")
	ret0, _ := ret[0].(crdt.CRDT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCRDT indicates an expected call of CreateCRDT.
func (mr *MockDeltaMockRecorder) CreateCRDT() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCRDT", reflect.TypeOf((*MockDelta)(nil).CreateCRDT))
}

// MarshalJSON mocks base method.
func (m *MockDelta) MarshalJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalJSON indicates an expected call of MarshalJSON.
func (mr *MockDeltaMockRecorder) MarshalJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalJSON", reflect.TypeOf((*MockDelta)(nil).MarshalJSON))
}

// Merge mocks base method.
func (m *MockDelta) Merge(other crdt.Delta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", other)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockDeltaMockRecorder) Merge(other any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockDelta)(nil).Merge), other)
}

// Type mocks base method.
func (m *MockDelta) Type() crdt.CRDTType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(crdt.CRDTType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockDeltaMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockDelta)(nil).Type))
}

// UnmarshalJSON mocks base method.
func (m *MockDelta) UnmarshalJSON(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalJSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalJSON indicates an expected call of UnmarshalJSON.
func (mr *MockDeltaMockRecorder) UnmarshalJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalJSON", reflect.TypeOf((*MockDelta)(nil).UnmarshalJSON), data)
}
