services:
  node-1:
    container_name: node-1
    cpus: "2.0"
    mem_limit: "1Gb"
    mem_reservation: "512Mb"  # мягкий лимит, контейнер попробует держаться ниже
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./wal_data_1:/wal_data
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    networks:
      - cluster_network

  node-2:
    container_name: node-2
    cpus: "2.0"
    mem_limit: "1Gb"
    mem_reservation: "512Mb"  # мягкий лимит, контейнер попробует держаться ниже
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50052:50051"
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./wal_data_2:/wal_data
    command: [ "./lume", "--config", "./configs/config2.yaml" ]
    networks:
      - cluster_network


networks:
  cluster_network:
    driver: bridge