services:
  node-1:
    container_name: node-1
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
  node-2:
    container_name: node-2
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50052:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    networks:
      - cluster_network
  node-3:
    container_name: node-3
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50053:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    networks:
      - cluster_network
  node-4:
    container_name: node-4
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50054:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network

  node-5:
    container_name: node-5
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50055:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
  node-6:
    container_name: node-6
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50056:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
  node-7:
    container_name: node-7
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50057:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
  node-8:
    container_name: node-8
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50058:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
  node-9:
    container_name: node-9
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50059:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
  node-10:
    container_name: node-10
    build:
      context: ../
      dockerfile: local_tests/Dockerfile
    ports:
      - "50060:50051"
    environment:
      - LOG_LEVEL=DEBUG
    command: [ "./lume", "--config", "./configs/config1.yaml" ]
    depends_on:
      - node-2
      - node-3
    networks:
      - cluster_network
#  node-11:
#    container_name: node-11
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50061:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-12:
#    container_name: node-12
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50062:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-13:
#    container_name: node-13
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50063:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-14:
#    container_name: node-14
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50064:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-15:
#    container_name: node-15
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50065:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-16:
#    container_name: node-16
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50066:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-17:
#    container_name: node-17
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50067:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-18:
#    container_name: node-18
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50068:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-19:
#    container_name: node-19
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50069:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network
#  node-20:
#    container_name: node-20
#    build:
#      context: ../
#      dockerfile: local_tests/Dockerfile
#    ports:
#      - "50070:50051"
#    environment:
#      - LOG_LEVEL=DEBUG
#    command: [ "./lume", "--config", "./configs/config1.yaml" ]
#    networks:
#      - cluster_network

networks:
  cluster_network:
    driver: bridge

