syntax = "proto3";

package transport;

option go_package = "pkg/transport/grpc/transportpb";

import "google/protobuf/empty.proto";

message Range {
  uint64 start = 1;
  uint64 end = 2;
}

message RangeList {
  repeated Range ranges = 1;
}

message GetRequest{
  map<string, RangeList> versions = 1;
}

message GetResponse{
  repeated bytes updates = 1;
}

message PublishRequest{
  repeated bytes updates = 1;
}

message GetVersionVectorResponse {
  map<string, uint64> VectorClock = 1;
}

message RestoreSeqRequest {
  string node_id = 1;
}

service Updates {
  rpc Publish(PublishRequest) returns (google.protobuf.Empty);
  rpc RestoreSeq(RestoreSeqRequest) returns (google.protobuf.Empty);
  rpc Get(GetRequest) returns (GetResponse);
  rpc GetVersionVector(google.protobuf.Empty) returns (GetVersionVectorResponse);
}