node:
  id: "node2"
  bind_address: "127.0.0.2"
  port: 9092
seeds:
  - "127.0.0.1"
gossip:
  port: 443 # TODO set in gossip
  fanout: 3
  interval: 30000
  retries: 2
persistence:
  wal_dir: ./wal_data_2