node:
  id: "node2"
  bind_address: "127.0.0.2"
  port: 50051
seeds:
  - "127.0.0.1"
gossip:
  port: 50052
  fanout: 3
  interval: 30000
  retries: 2
membership:
  port: 50053
persistence:
  wal:
    path: ./wal_data1
    segment_threshold: 1000
trace:
  enable: false

# TODO external/client port, gossip port, membership port