// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package storage

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// UpdateTypeDelta is a UpdateType of type Delta.
	// delta update of crdt type to merge
	UpdateTypeDelta UpdateType = "Delta"
	// UpdateTypeSet is a UpdateType of type Set.
	// set key to new value
	UpdateTypeSet UpdateType = "Set"
	// UpdateTypeDelete is a UpdateType of type Delete.
	// delete key
	UpdateTypeDelete UpdateType = "Delete"
)

var ErrInvalidUpdateType = errors.New("not a valid UpdateType")

// String implements the Stringer interface.
func (x UpdateType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UpdateType) IsValid() bool {
	_, err := ParseUpdateType(string(x))
	return err == nil
}

var _UpdateTypeValue = map[string]UpdateType{
	"Delta":  UpdateTypeDelta,
	"delta":  UpdateTypeDelta,
	"Set":    UpdateTypeSet,
	"set":    UpdateTypeSet,
	"Delete": UpdateTypeDelete,
	"delete": UpdateTypeDelete,
}

// ParseUpdateType attempts to convert a string to a UpdateType.
func ParseUpdateType(name string) (UpdateType, error) {
	if x, ok := _UpdateTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _UpdateTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return UpdateType(""), fmt.Errorf("%s is %w", name, ErrInvalidUpdateType)
}

// MarshalText implements the text marshaller method.
func (x UpdateType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UpdateType) UnmarshalText(text []byte) error {
	tmp, err := ParseUpdateType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *UpdateType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
