// Code generated by MockGen. DO NOT EDIT.
// Source: updates_buffer.go
//
// Generated by this command:
//
//	mockgen -source=updates_buffer.go -destination=mocks/buffer.mock.go UpdatesBuffer
//

// Package mock_updates_buffer is a generated GoMock package.
package mock_updates_buffer

import (
	storage "in-memorydb/pkg/storage/types"
	structs "in-memorydb/pkg/structs"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdatesBuffer is a mock of UpdatesBuffer interface.
type MockUpdatesBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatesBufferMockRecorder
	isgomock struct{}
}

// MockUpdatesBufferMockRecorder is the mock recorder for MockUpdatesBuffer.
type MockUpdatesBufferMockRecorder struct {
	mock *MockUpdatesBuffer
}

// NewMockUpdatesBuffer creates a new mock instance.
func NewMockUpdatesBuffer(ctrl *gomock.Controller) *MockUpdatesBuffer {
	mock := &MockUpdatesBuffer{ctrl: ctrl}
	mock.recorder = &MockUpdatesBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatesBuffer) EXPECT() *MockUpdatesBufferMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUpdatesBuffer) Get(key, nodeID string) ([]*storage.Update, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, nodeID)
	ret0, _ := ret[0].([]*storage.Update)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUpdatesBufferMockRecorder) Get(key, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUpdatesBuffer)(nil).Get), key, nodeID)
}

// GetCovering mocks base method.
func (m *MockUpdatesBuffer) GetCovering(nodeID string, r structs.Range) []*storage.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCovering", nodeID, r)
	ret0, _ := ret[0].([]*storage.Update)
	return ret0
}

// GetCovering indicates an expected call of GetCovering.
func (mr *MockUpdatesBufferMockRecorder) GetCovering(nodeID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCovering", reflect.TypeOf((*MockUpdatesBuffer)(nil).GetCovering), nodeID, r)
}

// Len mocks base method.
func (m *MockUpdatesBuffer) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockUpdatesBufferMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockUpdatesBuffer)(nil).Len))
}

// PeekN mocks base method.
func (m *MockUpdatesBuffer) PeekN(n int) []*storage.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekN", n)
	ret0, _ := ret[0].([]*storage.Update)
	return ret0
}

// PeekN indicates an expected call of PeekN.
func (mr *MockUpdatesBufferMockRecorder) PeekN(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekN", reflect.TypeOf((*MockUpdatesBuffer)(nil).PeekN), n)
}

// Put mocks base method.
func (m *MockUpdatesBuffer) Put(updates ...*storage.Update) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range updates {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Put", varargs...)
}

// Put indicates an expected call of Put.
func (mr *MockUpdatesBufferMockRecorder) Put(updates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockUpdatesBuffer)(nil).Put), updates...)
}

// Remove mocks base method.
func (m *MockUpdatesBuffer) Remove(key, nodeID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", key, nodeID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockUpdatesBufferMockRecorder) Remove(key, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockUpdatesBuffer)(nil).Remove), key, nodeID)
}

// RemoveN mocks base method.
func (m *MockUpdatesBuffer) RemoveN(n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveN", n)
	ret0, _ := ret[0].(int)
	return ret0
}

// RemoveN indicates an expected call of RemoveN.
func (mr *MockUpdatesBufferMockRecorder) RemoveN(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveN", reflect.TypeOf((*MockUpdatesBuffer)(nil).RemoveN), n)
}
