// Code generated by MockGen. DO NOT EDIT.
// Source: gossip.go
//
// Generated by this command:
//
//	mockgen -source=gossip.go -destination=mocks/gossip.mock.go Gossip
//

// Package mock_gossip is a generated GoMock package.
package mock_gossip

import (
	context "context"
	gossip "github.com/kestfor/in-memorydb/pkg/gossip"
	structs "github.com/kestfor/in-memorydb/pkg/structs"
	types "github.com/kestfor/in-memorydb/pkg/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGossip is a mock of Gossip interface.
type MockGossip struct {
	ctrl     *gomock.Controller
	recorder *MockGossipMockRecorder
	isgomock struct{}
}

// MockGossipMockRecorder is the mock recorder for MockGossip.
type MockGossipMockRecorder struct {
	mock *MockGossip
}

// NewMockGossip creates a new mock instance.
func NewMockGossip(ctrl *gomock.Controller) *MockGossip {
	mock := &MockGossip{ctrl: ctrl}
	mock.recorder = &MockGossipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGossip) EXPECT() *MockGossipMockRecorder {
	return m.recorder
}

// AsyncSend mocks base method.
func (m *MockGossip) AsyncSend(ctx context.Context, data []*types.Update) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncSend", ctx, data)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// AsyncSend indicates an expected call of AsyncSend.
func (mr *MockGossipMockRecorder) AsyncSend(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncSend", reflect.TypeOf((*MockGossip)(nil).AsyncSend), ctx, data)
}

// GetVersionVector mocks base method.
func (m *MockGossip) GetVersionVector(ctx context.Context, peer types.Node) (*gossip.VersionVectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionVector", ctx, peer)
	ret0, _ := ret[0].(*gossip.VersionVectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionVector indicates an expected call of GetVersionVector.
func (mr *MockGossipMockRecorder) GetVersionVector(ctx, peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionVector", reflect.TypeOf((*MockGossip)(nil).GetVersionVector), ctx, peer)
}

// Pull mocks base method.
func (m *MockGossip) Pull(ctx context.Context, peer types.Node, versions map[string][]structs.Range) ([]*types.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, peer, versions)
	ret0, _ := ret[0].([]*types.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockGossipMockRecorder) Pull(ctx, peer, versions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockGossip)(nil).Pull), ctx, peer, versions)
}

// Send mocks base method.
func (m *MockGossip) Send(ctx context.Context, data []*types.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockGossipMockRecorder) Send(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockGossip)(nil).Send), ctx, data)
}

// Shutdown mocks base method.
func (m *MockGossip) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGossipMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGossip)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockGossip) Start(ctx context.Context) (chan<- []*types.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(chan<- []*types.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockGossipMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockGossip)(nil).Start), ctx)
}
